# Generated by Django 3.2.8 on 2022-05-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220501_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
