# Generated by Django 4.0.4 on 2022-05-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_accountdetails_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='username',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
