# Generated by Django 4.0.4 on 2022-05-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_accountdetails_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
