# Generated by Django 4.0.4 on 2022-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userdata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
