# Generated by Django 4.0.4 on 2022-05-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_userdata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
