# Generated by Django 4.0.4 on 2022-05-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userdata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_details', to='main.userdata'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
